### ISSUE TITLE
Importing Theme 

### ISSUE THREAD

**Issue by vibhi19** [glitch-soc/mastodon#1084]
I wanted a theme from mastodon.technology, its vanilla theme i copied the file and what other changes i have to make to get that theme show up in Mastodon settings. I recompiled but its not showing up and i think i need to make few more changes can someone guide me on this.

**Comment by ThibG** [comment]
https://glitch-soc.github.io/docs/features/themes/
This should cover your needs and still be up to date

**Comment by vibhi19** [comment]
I am sorry but i didn't understand  i copied wooly theme from https://github.com/ashfurrow/mastodon/tree/master/app/javascript/styles
and pasted it in /app/javascript/styles.  is this right? or i have to paste it into javascript/skins/vanilla

and is there anything else i have to do or not?

**Comment by ThibG** [comment]
As stated by the documentation I have linked you, glitch-soc skins behave differently than mastodon themes.
They live in `app/javascript/skins/<flavour>/<skin>`. They're basically made of a `common.scss`. Read one of them to know how to import skins from `app/javascript/styles/`.
Furthermore, a skin for the `vanilla` flavour might not work correctly for the `glitch` flavour, as the markup is different in places.

**Comment by vibhi19** [comment]
One question can mastodon vanilla theme can be used in Glitch fork or not?

**Comment by ThibG** [comment]
glitch-soc features two front-ends, called flavours. One is the “vanilla” flavour, the one used upstream with almost no modification, and the other is the “glitch” flavour which is the default and features lots of changes/improvements.

glitch-soc's theming system is different from Mastodon's, instead of themes there are flavours (as discussed earlier) and skins. The bulk of themes written for upstream Mastodon can be used with the vanilla flavour by using simple “skins” to wrap them, as is done with built-in themes. This happens in `app/javascript/skins/vanilla`. Skins for the “glitch” flavour work in a similar way, but porting a skin from vanilla to glitch may be more involved.

**Comment by vibhi19** [comment]
it is quite easy 

First Download Vanilla Theme, 

and put the file in app/javascript/styles

Then create a folder javascript/skins/vanilla with that theme name 

Create Two file with "common.scss"  and "name.yml"

> @import 'styles/woolly';

Put  upper code in common.scss and change woolly with your theme name

> en:
>   skins:
>     vanilla:
>       woolly: Woolly

Put upper code in name.yml and change woolly name with your own theme name check other file if have any confusion

and Recompile you will get your theme.

is there some nice theme for Glitch or not?
