### ISSUE TITLE
Migration instructions too vauge 

### ISSUE THREAD

**Issue by Laurelai** [glitch-soc/mastodon#1113]
Due to mainline mastodons multiple refusals to add user desired features and changes many people will be looking for forks that might be more willing to listen to the userbase. Glitch is one such fork mentioned. However your migration instructions are quite vauge and there have been no tagged releases since 2017, Sometimes specific releases have special upgrade instructions and we dont want to break our instances in the migration so some clearer step by step instructions would help a lot of instance admins, myself included.

**Comment by ashkitten** [comment]
following mainline upgrade instructions up to their latest release, then switching to glitchsoc and running migrations should work fine. i don't recall any specific upgrade instructions in recent releases, anyways.

**Comment by Laurelai** [comment]
> following mainline upgrade instructions up to their latest release, then switching to glitchsoc and running migrations should work fine. i don't recall any specific upgrade instructions in recent releases, anyways.

See specifying you have to update mastodon to the latest release is good information that should be on the install guide.

As well as whatever commands you might need to switch the git repos to the new one.

**Comment by ThibG** [comment]
Updating Mastodon to the latest release is not required. So far, migrating from one version to another only required a subset of what is described in the glitch-soc documentation, and doing the extra steps does not hurt.

As for commands for switching git repos… yeah, I should probably add something along those lines, although it's a bit tricky because some people would strictly follow upstream, and some would have merged their own changes.

**Comment by ThibG** [comment]
I don't know if that covers everything you want the documentation to have, but I'm not sure what else should be added: https://github.com/glitch-soc/docs/pull/36

**Comment by ThibG** [comment]
I have updated the documentation. Please reopen if it's not enough for you.
