### ISSUE TITLE
Better user friendly setting for Glitch 

### ISSUE THREAD

**Issue by vibhi19** [glitch-soc/mastodon#1137]
Make Below setting as defaul in Glitch as its better for new user and provide a High Quality Experience

![Setting 2](https://user-images.githubusercontent.com/31093426/59968164-c961d680-9552-11e9-9e19-8f8cd2adcacb.jpeg)
![Setting](https://user-images.githubusercontent.com/31093426/59968168-cebf2100-9552-11e9-892c-c9195c45622e.jpeg)

**Comment by ThibG** [comment]
There are reasons why the following settings have their defaults:
- collapsing long toots and notifications:well, long toots can be a pain because of the space they take in your TL, auto-collapsing them makes sense. Auto-collapsing notifications as well, as that applies to messages the user wrote, and are in most cases recent, so the user can usually remember the context
- display an estimate of the reply count: it's not enabled by default because it provides a very inaccurate and often stale number of replies: those are the numbers of replies known by your instance at the time it was sent to the client. So most of the time, 0. Unless it's a boost, that is.
- High color privacy icons: it's off by default because they are likely to be an issue with colorblind people
- unread notifications badge: this is something likely to make glitch-soc more addictive or anxiety-inducing, so it is disabled by default
- notifications favicon badge: same as above, but worse

**Comment by vibhi19** [comment]
Hello and Thanks for the reply,

You got few valid point points but as admin we should also have some level of control what if many user asking to make it default. So it will better if you guide us on making our setting default on our intstance. You are taking everyone in perspective but as admin we are taking our user in perspective for us they are important. There is an option to tell everyone but people dont want to do the work so it became much hard.

and One suggestion for Auto-collapsing, collapse only those toots which has more than 500 words and  bigger toot also show 500 char and if some one want to read full toot he should use the button.

**Comment by ThibG** [comment]
I think those defaults are sane, if you disagree with some of them, we can discuss it (you may reopen this issue with arguments).

I'm unsure about adding some mechanism to let admins change the defaults, but if you want to change them, you can edit `app/javascript/flavours/glitch/reducers/local_settings.js`
