### ISSUE TITLE
Hyperlinks can conceal actual link target

### ISSUE THREAD

**Issue by rtucker** [glitch-soc/mastodon#1162]
The appearance of a link auto-generated from a URL and of an embedded hyperlink are identical, which makes it trivial to create misleading links:

![Screenshot_20190715-172215](https://user-images.githubusercontent.com/97437/61250371-834cfc80-a725-11e9-9cca-c0e28b06ca16.png)
![Screenshot_20190715-172224](https://user-images.githubusercontent.com/97437/61250381-87791a00-a725-11e9-9008-001d3e57c077.png)

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment]
I don't see that as a huge issue, it has always been like that (in gltich-soc and upstream), and I'm not too sure what we could do about it (apart from discarding link text, but I'm not ok with that).
Suggestions are welcome though

**Comment by Felthry** [comment]
I'd suggest a small UI element to indicate that it's not an auto-generated link. Similar to how Mediawiki has its little "external link" icon.

**Comment by ThibG** [comment]
Ok, I will look into that. It is kinda hard to know what is an auto-generated link, though, as *all* links are formatted by the originating instance, and the exact way it is formatted depends on the software used.

**Comment by rtucker** [comment]
Hm... could put the domain of a link after the link, e.g.

`Simply log into [trustworthy.example.com/](https://shadyco.example.com/phish/doom/) to pet the dog`

renders to:

> Simply log into [trustworthy.example.com/](https://shadyco.example.com/phish/doom/) `[shadyco.example.com]` to pet the dog

(can be smaller, optional, etc)

**Comment by Laurelai** [comment]
> I don't see that as a huge issue, it has always been like that (in gltich-soc and upstream), and I'm not too sure what we could do about it (apart from discarding link text, but I'm not ok with that).
> Suggestions are welcome though

Its actually a huge security issue. Theres all kinds of attacks that can be enacted with this bug and its a matter of when not if this happens and how much harm is done.

**Comment by jakimfett** [comment]
> ...the exact way it is formatted depends on the software used...

The Markdown spec is non-ambiguous on how links are to be formatted, or am I to understand that the intention is something other than a subset of the Markdown rules for links?


---

>  I don't see that as a huge issue, it has always been like that...

Clearly, it's always been broken, so we must leave it as-is.  
`</sarcasm>`

Humor aside, @rtucker 's suggestion is a massive improvement, but still depends on the end user noticing that the link is different than the tag beside it.

And, users are so used to warnings that I've seen users click through as many as five layers of information intended to protect them from their own actions, and then immediately complain to their admin about the results.

Would adjusting the link colours as well be a good visual, i.e.  
> `A bare link is untagged (and gold): [trusty.link/my-legit-page]`  
> becomes [trusty.link]  

however

> `An adjusted link is tagged (and orange): [trusty.link](malic.ous/url)`  
> becomes [malici.ous (masked as trusty.link) ]


---

Remember, a rather large chunk of the target audience is basically the multicultural [Jessica](https://swiftonsecurity.tumblr.com/post/98675308034/a-story-about-jessica), but with added vulnerability of being a pre-marginalized individual who has already been abused by 'modern' for-profit social media sites.


---

The intent is to give the end user an immediate way of identifying that 'this link requires extra scrutiny', because as @Laurelai stated, this is a huge security concern, and it's only a matter of time before there's a swarm of this year's variant of cryptolocker propagating via federated links behind a user-opaque mask.

**Comment by ThibG** [comment]
> > ...the exact way it is formatted depends on the software used...
> 
> The Markdown spec is non-ambiguous on how links are to be formatted, or am I to understand that the intention is something other than a subset of the Markdown rules for links?

I fail to see why you brought up the Markdown spec here. Mastodon (and glitch-soc) receives status contents in HTML, and links can be formatted in any number of way. Mastodon itself formats auto-links in a very particular way:

```html
<a href="https://domain/long/path" rel="noopener" target="_blank" class="status-link" title="https://domain/long/path"><span class="invisible">https://</span><span class="ellipsis">domain/long</span><span class="invisible">/path</span></a>
```

Other software could do otherwise, so figuring out if a link is “misleading” is already non-trivial.

> > I don't see that as a huge issue, it has always been like that...
> 
> Clearly, it's always been broken, so we must leave it as-is.
> `</sarcasm>`

I mean, the one one hand, if we can draw attention to misleading links, great, on the other hand, it's always been like that on Mastodon, on any website, in any email, etc.

Also, does anyone feel like bringing the issue upstream, as it's definitely not specific to glitch-soc?

**Comment by ThibG** [comment]
I am not sure I want to go this way, as it mangles all links this way and there is no option to turn it off, but monsterpit does something interesting in that regard: https://monsterpit.net/@multiple_creatures/102502930163933891

**Comment by jakimfett** [comment]
hiding metadata obscures the problem, 
presenting relevant (gently-abstracted) metadata gives the user [agency](https://en.wikipedia.org/wiki/Agency_(philosophy)).

---

This is *not* about:
"figure out if the link is malicious/malformed/etc and alert the user", 

the emphasis is on 
"**presenting the user with enough link metadata to inform their navigation decisions**" 


Meaning there's no "special case" to handle, just "how links always should look".

> Unless you want bare/formatted links to look different, as I mentioned in my [comment previously](https://github.com/glitch-soc/mastodon/issues/1162#issuecomment-511619342).

And, this could also help with link shortener abuses 
(eg, a `goo.gl/<hash>` link leading to `mali.cious.site/malware`).

---

> @ThibG commented:
> ...I fail to see why you brought up the Markdown spec...

Because the [original issue report used Markdown spec linking](https://github.com/glitch-soc/mastodon/issues/1162#issue-468342901), and you didn't see fit to object at that time.

**The point is how the link (meta) data is presented to the user,** 
not "what formats can be parsed by the external linker", 
although that second bit is adjacent, and I understand your confusion.

---

> @ThibG also commented:
> ...on the other hand, it's always been like that...

What I see is you saying (for the second time) that because this is broken (and has been for a while), that leaving it broken is a potential resolution.

Unfortunately, I was under the impression that glitch-soc was about improving the paradigm and experience of social media users as they flee centralized/monetized/abuse-normalized platforms.

Note that you have at least one (possibly three?) information security professionals waving the "THIS IS A PROBLEM" flag at you.  
What you choose to do with that is...obviously...your choice.

---

tldr - default link metadata presentation tweaks would fix the root issue

**Comment by no-boot-device** [comment]
imo this should be done by having a hover tooltip that appears when you mouse over a link, so as not to clash
any solution will not be able to affect mobile apps anyway, obviously, as they choose to render hyperlinks as they wish

**Comment by jakimfett** [comment]
Upstream issues can be and are influenced by what gets fixed, first, in a downstream like this.

Hover tooltips hide the info from mobile and keyboard navigation users, and should be avoided in an intentionally accessible interface.

Mobile apps are definitely out of spec, but having a standard-ish way to do this can affect their decisions to deviate from a norm established by the server software, and mobile browser users very much *are* affected by this.

**Comment by ThibG** [comment]
> Meaning there's no "special case" to handle, just "how links always should look".

There is, unless you want all auto-generated links to look like something like `github.com/glitch-soc/mastodon… (github.com)`.

> And, this could also help with link shortener abuses
> (eg, a `goo.gl/<hash>` link leading to `mali.cious.site/malware`).

I'm sorry I can't see how that's related. Do you want us to fetch the link and record any redirection?

> > @ThibG commented:
> > ...I fail to see why you brought up the Markdown spec...
> 
> Because the [original issue report used Markdown spec linking](https://github.com/glitch-soc/mastodon/issues/1162#issue-468342901), and you didn't see fit to object at that time.
> 
> **The point is how the link (meta) data is presented to the user,**
> not "what formats can be parsed by the external linker",
> although that second bit is adjacent, and I understand your confusion.

Yes, I understand that, so I still don't know why you brought Markdown up.
Messages received by glitch-soc are already-formatted HTML, and the exact way links are formatted depends on the authoring software.

For instance, Mastodon formats links as:
`<a href="https://domain/long/path" rel="noopener" target="_blank" class="status-link" title="https://domain/long/path"><span class="invisible">https://</span><span class="ellipsis">domain/long</span><span class="invisible">/path</span></a>`

We want to parse that to avoid having a redundant tag on every single link. And we can't just get the text and ignore the markup, because the `invisible` class could be used to bypass a text-based check.

> imo this should be done by having a hover tooltip that appears when you mouse over a link, so as not to clash

All links that or not recognized as mentions and hashtags by the WebUI currently *have* a hover tooltip with the full URL, both in glitch-soc and upstream. This is obviously not useful for mobile, though, and it is too subtle of a hint anyway when links are misleading.

**Comment by no-boot-device** [comment]
>All links that or not recognized as mentions and hashtags by the WebUI currently have a hover tooltip with the full URL, both in glitch-soc and upstream

I was being semi-tongue-in-cheek, yes.     
However, a JS tooltip that appears immediately instead of taking 2 seconds to appear would be nice.

**Comment by clarfon** [comment]
It seems silly, but why not just open a modal by default when a link's text doesn't match its target? It could be disablable but it'd help a lot to inform users where lines go.

**Comment by no-boot-device** [comment]
That's the issue: We don't know if a link's text doesn't match its target because the nature of markdown

**Comment by clarfon** [comment]
You can with JavaScript.

**Comment by no-boot-device** [comment]
...No, you can't? We've already explained this upthread.

**Comment by ThibG** [comment]
Regarding figuring out the link's visible text: it is tricky, but I think I managed to do it in https://github.com/tootsuite/mastodon/pull/11426

Design issues remain, but that was the main technical difficulty imho

**Comment by no-boot-device** [comment]
@ThibG [https://accounts.youtube.com/watch?v=dQw4w9WgXcQ](https://accounts.youtube.com/accounts/SetSID?continue=https%3A//www.google.com/accounts/ServiceLogin%3Fservice%3Dah%26passive%3Dtrue%26continue%3Dhttps%3A//appengine.google.com/_ah/conflogin%253Fcontinue%253Dhttps%3A//smooch.computer/)

**Comment by ThibG** [comment]
@no-boot-device what you're asking for is something impossible

**Comment by ThibG** [comment]
My upstream PR (https://github.com/tootsuite/mastodon/pull/11426) has been accepted. What it does is rewrite, in the WebUI, every link in a status which text looks like an URL (or a shortened form like Mastodon outputs) and does not match the target. What it does not do is:
- Help in any way with spotting homograph attacks on International Domain Names
- Display information on the target for links with custom text not looking like a link
- Extract any information from link shorteners and redirects

I have not backported it to glitch-soc yet, and I'm not completely happy with the design in that upstream PR. I am considering implementing it as an option between:
- No rewriting or hint whatsoever (current behavior)
- Rewriting misleading links (upstream)
- Putting a tag with the target's hostname besides any link not matching it (my original proposal for upstream, would probably be the default)

What do you think of it?
