### ISSUE TITLE
re-draft

### ISSUE THREAD

**Issue by hoodieak** [glitch-soc/mastodon#122]
whenever looking at your own post you may click the '...' menu and click 're-draft' to edit and repost the toot

this would show a dialog with several options

first, a pair of radio buttons with the labels 'delete immediately' and 'delete upon reposting edited draft'
second, a trio of clickable buttons that all close the dialog "redraft entire self-thread' 'redraft this toot' and 'cancel'

clicking either of the first two copies either the thread (via thread-compose seen here https://github.com/glitch-soc/mastodon/issues/121) or the toot itself into the compose box, tooting deletes toot if radio button is selected (this should show above the compose box while composing re-drafted toot, as a warning if it will delete upon tooting edited post)

**Comment by marrus-sh** [comment]
Right now the API doesn't send the original plain-text version of toots, only the resulting HTML version. For this to work, we need the original plain-text version of the toot to also be sent for your own toots. (A name like `source`, `source.content`, or `source_content` would be idiomatic, since the plain-text version of account bios is offered as `source.note`).

**Comment by hoodieak** [comment]
we can close this! upstream did it and we have it i believe, im double check aaaaaaaaand yep
