### ISSUE TITLE
cancelling follow requests doesn't work

### ISSUE THREAD

**Issue by yungslime** [glitch-soc/mastodon#166]
It's pretty self explanatory - I set up a glitchsoc instance running the latest master a couple of days ago - a few follow requests had troubles federating so I tried cancelling them.

![image](https://user-images.githubusercontent.com/25403790/31424460-b447506c-ae5a-11e7-8144-97462cc545eb.png)

the alt-text is here but clicking the pending request button doesn't do anything

In my foolish troubleshooting attempts I also tried setting the button class to active instead of disabled using the chrome dev tools since that's the case on my standard mastodon install running v1.6.1, that doesn't do anything though.

**Comment by yipdw** [comment]
I can replicate this issue.  Interestingly, pressing the hourglass doesn't seem to result in _any_ activity, either client- or server-side.

**Comment by marrus-sh** [comment]
When we forked the account header from upstream, clicking the hourglass didn't do anything 😅

They've since changed that behaviour, compare [ours](https://github.com/glitch-soc/mastodon/blob/master/app/javascript/glitch/components/account/header.js#L145) to [theirs](https://github.com/tootsuite/mastodon/blob/master/app/javascript/mastodon/features/account/components/header.js#L105).

This doesn't look like too difficult of a fix—I'll try to get to it in a day or two (other glitchsoc devs: feel free to take this from me if you think you can get it done sooner)

**Comment by marrus-sh** [comment]
This should be fixed now (it was a little while ago but I forgot to say anything)~

Lmk if there are still issues~
