### ISSUE TITLE
Status content alignment (below profile picture, different from vanilla)

### ISSUE THREAD

**Issue by kescherCode** [glitch-soc/mastodon#1814]
### Steps to reproduce the problem

1. View a (non-detailed/highlighted) post/status, either on the React Web UI or *the other one*.
2. Compare how it looks between [vanilla](https://mastodon.social/@kudos/535449) and [glitch-soc](https://catcatnya.com/@kescher/108619095396297769). (visually compare the the post that is being replied to, not the one directly linked to)

This issue is inspired by https://eldritch.cafe/@amberage/108701788445942790. I do suspect this difference may intentional, but in case it isn't, I am opening this as a bug report, as I agree that it feels a bit off.

### Expected behaviour

Text content should start right after the profile picture as in vanilla

### Actual behaviour

Text content starts below the profile picture

### Specifications

85d0e3474574d82fc653925560d2905cee43287e, but has been like this for a long time.

My browser is Firefox 102.0.1, but that doesn't matter (occurs in basically all browsers).

**Comment by ClearlyClaire** [comment]
As far as I remember, this comes from before I even touched glitch-soc and is intentional.

Although I cannot find the rationale, I imagine this is both to avoid wasted space and to enable displaying people's display name and handle on separate lines. Those are at least reasons why I appreciate this design over upstream's design, and I do not intend to change it.
