### ISSUE TITLE
(CW: Death) : Could Administrator accounts be also turn into memoriam too?

### ISSUE THREAD

**Issue by MxFraud** [glitch-soc/mastodon#1831]
### Pitch

I remember why we had the Memoriam feature introduced.
Being able to turn a "normal" profile into something else when the people we shared a bond are not with us is actually a very good.

I've been waiting nearly a year I've been meant to ask (because I couldn't quite come to terms with it).
But yeah, it would be nice to be able to turn admin account into memoriam.

I've not even looked at other issues or if it has been discussed, I feel like there could be some technical reason it is not possible (from the UI at least).
We use v3.4.6+ if that helps

### Motivation

I would help me personally

**Comment by ClearlyClaire** [comment]
I am sorry about the circumstances…

It is indeed not possible from the administration UI, because turning an account into a memorial disables that account, and generally speaking, we don't allow actions on someone of your rank or above to avoid hijacking a server's administration.

I think the easiest way you can deal with that is demoting that person's account by doing `tootctl accounts modify <username> --role=user`, then turn the account into a memorial from the administration UI.

**Comment by MxFraud** [comment]
Ok, I'll do that.
Thank you
