### ISSUE TITLE
Cancelling a follow request says "unfollow" instead of "cancel"

### ISSUE THREAD

**Issue by mxamber** [glitch-soc/mastodon#1869]
### Steps to reproduce the problem

1. enable unfollow confirmation dialog
2. follow request someone
3. withdraw the request before it is approved

### Expected behaviour

The dialog should say something along the lines of "Are you sure you want to cancel your follow request?"

### Actual behaviour

The button says "unfollow" as if your request had already been approved and you were about to unfollow.

### Specifications

Glitch 3.5.3

**Comment by prplecake** [comment]
This is likely an upstream issue.

**Comment by prplecake** [comment]
This is an upstream issue.

**Comment by mxamber** [comment]
Aye, I'll raise it there.

**Comment by mxamber** [comment]
https://github.com/mastodon/mastodon/issues/19361

**Comment by prplecake** [comment]
It turns out this would need to be ported to the glitch frontend anyway. I'll open a port pr here when the upstream pr is merged. mastodon#19363

**Comment by ClearlyClaire** [comment]
I usually take care of ports when merging upstream changes, as it's generally easier to go through what needs porting that way.

That being said, merging from upstream is taking a while those days, because I was very busy with upstream work (groups) until a few weeks ago, and because Gargron has been merging a lot of questionable and unfinished changes that touch most of the interface (replacing most of the server-side rendered pages with logged-out access to the react WebUI and redesigning many aspects of the mobile layout in the process), and I'm not too sure how to deal with them yet.
