### ISSUE TITLE
Pinned toots 😘

### ISSUE THREAD

**Issue by marrus-sh** [glitch-soc/mastodon#19]
So I wanted to start an issue for pinned toots and I think there are two approaches we can take to them, but as they have completely different implementations it would be good to have some on-record discussion, yeah? The approaches I see are,,

## Traditional pinned toots

AKA what Twitter has. Pawoo has already implemented this, although I'm assuming (?? does anyone know??) that it doesn't federate? But anyway, this one is pretty easy imo, it can be achieved just adding a `link` field to the user's contact info that links to the pinned toot, and then adding that to the Accounts API. There's a lot you can do with this too: forbidding mentions or links to other toots in pinned toots, for example. It should federate easily and is pretty straightforward.

The downside to this approach is that you are limited to one, or at most a small number, of pinned toots per user.

## “Pinned”/“Featured” timelines

Alternatively, we could allow users to “feature” their own toots in a Featured Timeline. We could implement this locally fairly simply by just making the Featured Timeline all of a user's own toots that they have favourited; i.e., when you click the star on your own toot, it gets added to your Featured Timeline.

This would be super cool for like artists and such because they could feature just the posts with their own art (better than media timelines which include art from all sources), and it would allow people to feature toots with variable visibilities that different people can see.

The downside is that, unless I'm mistaken (I might be tbf), favourites don't federate, so the Featured Timeline would only be available locally without significant backend work (i.e., federating favourites that a user has made on their own toots). So we would have to work on that.

It's also a little harder to impose restrictions on what toots you can feature if we're gonna tie it to favouriting. Not impossible though.

- - -

Of course we could implement *both* of these options if we really wanted. But I figured discussion would be good. I want something to happen with this lol 😅

**Comment by nightpool** [comment]
> The downside to this approach is that you are limited to one, or at most a small number, of pinned toots per user.

pawoo lets you have as many as you want, FYI. It's not great from a UX standpoint tho lol :P

**Comment by marrus-sh** [comment]
I meant with respect to federation—hypothetically you could stick a hundred link tags in someone's account info but I think that we should probably try to limit people having portable contacts that are hundreds of lines long ;)

That depends on implementation though. Maybe there's another way of doing it ?

**Comment by haniawni** [comment]
I really like that you've kicked off this conversation, thank you!

Of the two as presented, *I'm more a fan of the former* (limited to a small
number of toots), as it will be more reasonably understandable to
birdsite-flight new tooters as a "pinned toot", and can reasonably be even
rendered as such in the UI.

The other design, with the "featured timeline", actually strikes me quite a
bit like Tumblr profiles using personal tags, where your profile might
simply have a link for each tag of interest
this sounds like it, whether implemented via the favs-of-own-toots list or
search-a-hashtag-by-a-user-or-vice-versa, is meeting a distinct need from
pinned toots in the first place?
it also sounds like itd be a more involved build?
that said, if a "featured tags" approach is used instead of "faved own
toots", the profile-side changes are much easier (list of tags?), and
assuming the search-by-user-and-tag thing gets added to search, it natually
folds in with even stuff like adding addll colums to follow user-tag



-Hani Awni
UIUC Bs EE 2017 (biomechanics, social justice, robotics)
UIUC Bs 'CS' 2013 (BCI, AI, DBs, computational neuroethology)

**Comment by haniawni** [comment]
I really like that you've kicked off this conversation, thank you!

Of the two as presented, ***I'm more a fan of the former*** (limited to a small
number of toots), as it will be more reasonably understandable to
birdsite-flight new tooters as a "pinned toot", and can reasonably be even
rendered as such in the UI.

The other design, with the "featured timeline", actually strikes me quite a
bit like Tumblr profiles using personal tags, where your profile might
simply have a link for each tag of interest
this sounds like it, whether implemented via the favs-of-own-toots list or
search-a-hashtag-by-a-user-or-vice-versa, is meeting a distinct need from
pinned toots in the first place?
it also sounds like itd be a more involved build?
that said, if a "featured tags" approach is used instead of "faved own
toots", the profile-side changes are much easier (list of tags?), and
assuming the search-by-user-and-tag thing gets added to search, it natually
folds in with even stuff like adding addll colums to follow user-tag

**Comment by marrus-sh** [comment]
if we got search-by-hashtag-by-a-user, we could make it so that hashtag links in bios were just limited to that user, and that would work just as well or better than what I proposed, tbh. a self-favourited timeline would require federating more stuff and so be complicated to pull off.

in that case though I would agree that a more traditional pinned toot would be nice as well.

**Comment by yipdw** [comment]
Pinned toots have been available in upstream for a while now; is this issue still relevant?  (Should it be re-titled to e.g. "Implement featured timeline"?)

**Comment by marrus-sh** [comment]
Do pinned toots federate? Right now the only pinned toots you can see in the web view are your own (afaik) so I don't know the answer to this but if not, that's the important outstanding missing feature

**Comment by yipdw** [comment]
As far as I can tell, they don't federate.  From `api/v1/statuses/pins_controller.rb`:

```ruby
  def create
    StatusPin.create!(account: current_account, status: @status)
    render json: @status, serializer: REST::StatusSerializer
  end 

  def destroy
    pin = StatusPin.find_by(account: current_account, status: @status)
    pin&.destroy!
    render json: @status, serializer: REST::StatusSerializer
  end 
```

Creating or destroying a `StatusPin` doesn't dispatch any ActivityPub or OStatus-related tasks.  I'm not sure what the ActivityStreams representation of pin/unpin would be, though.  Maybe @nightpool has some ideas?

**Comment by marrus-sh** [comment]
well I don't think it's something that should be sent out as a status interaction (since it's really more user metadata) but more as just general profile information akin to statuses/follower/following counts

back in the old days everything was Portable Contacts and my understanding was that you could just use link fields to send that sort of information; now that we're activitypub and whatnot i don't know if that situation has changed (i'm not really a backend person anyway soo)

**Comment by ThibG** [comment]
Considering closing this issue since featured toots have been supported upstream and merged a while ago. They fit the first option and federate. There is nothing quite like the second option though.

**Comment by Fidgetcetera** [comment]
If anyone really really thinks this can be reopened, we or somebody else can, but let's go ahead and close it since it was presented as two options and the first option has been fully implemented.
