### ISSUE TITLE
Boosted posts bypass filtering

### ISSUE THREAD

**Issue by cottonpnut** [glitch-soc/mastodon#2053]
### Steps to reproduce the problem

1. have a specific word in a filter
2. a post containing that word gets boosted

### Expected behaviour

you dont see that post due to it being filtered

### Actual behaviour

you see that post on the timeline

### Detailed description

didnt know if this was a glitch issue or a mastodon issue and i think this is similar to #1900 but thats closed now.

i have 'nsfw' filtered completed and dont see those posts in my timeline except when they are boosted by others.
reloading filters it but shouldnt display it in the first place

### Specifications

mastodon: 4.0.2+glitch
vivaldi: 5.6.2867.50
os: linux

**Comment by ClearlyClaire** [comment]
I am unable to reproduce the issue. Can you still reproduce it?

**Comment by cottonpnut** [comment]
my filter:
![Screenshot_2023-01-04_12-08-28](https://user-images.githubusercontent.com/121609969/210552722-38f5c732-14d9-4cdd-8d97-33769a417962.png)

an example post that shows in my feed:
![Screenshot_2023-01-04_12-10-52](https://user-images.githubusercontent.com/121609969/210552945-abbe9a2b-fe87-45c1-87ae-25dd35e4dab9.png)

**Comment by Plastikmensch** [comment]
I'm also unable to reproduce this with current main.
Tried with local and remote toots and similar filter settings like in the screenshot.
Does the instance you're on have modifications which mess with filters or is it missing some updates?
The thing with running glitch is, it needs to be updated regularly.

However, if I set the filter to "Hide with a warning", filtered toots are hidden completely instead of showing with a warning in home.

**Comment by cottonpnut** [comment]
umm ok. closing as not reproducable
will discuss with instance admin
sorry

**Comment by gunfheum** [comment]
I'm the admin of the instance @cottonpnut is on
now running v4.1.0+glitch and it seems to happen only when a post that isn't known to the instance gets boosted and therefore now gets pushed to the feeds.
A refresh does filter them out, but its not ideal
