### ISSUE TITLE
video player bug

### ISSUE THREAD

**Issue by ncls7615** [glitch-soc/mastodon#260]
![unknown](https://user-images.githubusercontent.com/28977652/33841080-05d20cba-deda-11e7-8f7c-4314f5e5f56c.png)
glitch

![unknown 1](https://user-images.githubusercontent.com/28977652/33841107-19b30c84-deda-11e7-93e3-f6c23e1e3291.png)
vanilla

**Comment by ncls7615** [comment]
@marrus-sh can you check this?

**Comment by chriswmartin** [comment]
[This](https://github.com/chriswmartin/mastodon/commit/57d5520de1f02769551bf00050fd13e15ddd1a30) seems to fix the sizing issues for me (I don't know if its the best way to fix it though).

I'm also noticing a bug where if I try to expand a video in a detailed status I get a blank screen with the error "media.get is not a function" in the console.

**Comment by ncls7615** [comment]
it does not work for me...

**Comment by chriswmartin** [comment]
oh gosh you're right, sorry about that. I guess it only fixes it for me in conjunction with [this commit](https://github.com/chriswmartin/mastodon/commit/2820346ea99e270626bfd6aa9069269c3332abc0) -- regardless I'm sure its not the best way to fix this.

**Comment by ncls7615** [comment]
hmmmmm

**Comment by marrus-sh** [comment]
Right so the problem is that `<video>` elements don't preserve their aspect ratio by default, instead they have a default height of like `160px` or some such. It's really annoying lol.

Something that probably would be sufficient (just using CSS) would be to give the video a height of `100%` / whatever (stretch it as tall as makes sense in the context of the video modal) and then use `object-fit: contain`. That should preserve the intrinsic ratio (I think).

Alternatively, if we can discover the aspect ratio of the video via the API and/or the `HTMLVideoElement` (I don't know if that's provided or not), then we might be able to set the width via JavaScript. I'd need to dig into the code to see how that works.

**Comment by ncls7615** [comment]
probably it was fixed
<img width="2672" alt="2018-01-08 20 41 07" src="https://user-images.githubusercontent.com/28977652/34669309-55359f34-f4b4-11e7-8828-f3d33f474084.png">

**Comment by ncls7615** [comment]
probably this issue was fixed with [this commit](https://github.com/KnzkDev/mastodon/commit/6a73c8c8a290a9db7449b7a460701f726c400785)

**Comment by ncls7615** [comment]
Fixed in #329
