### ISSUE TITLE
Compose box is too narrow to show the word "toot"

### ISSUE THREAD

**Issue by yiskah** [glitch-soc/mastodon#34]
For some reason the compose box was made narrower on glitchsoc which I don't like personally but more importantly when you upload an image this is what happens:
![capture](https://user-images.githubusercontent.com/12243190/27647757-5be0313a-5bfa-11e7-92da-01fa05746ecc.JPG)

It's really cluttered and difficult to see all the small things and understand them and stuff. 

Solution: Return compose column to how it is on mainline or otherwise increase the width. I personally also find it weird and distracting how the column is now a box creating a massive color contrast in the empty space. My eyes are drawn there more than anything else and there's nothing there. 

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by dustine** [comment]
Can confirm that this issue seems to be related to the minimal size of the flexbox. On higher resolutions (1920x) it looks like this instead (bigger than on stable):

![image](https://user-images.githubusercontent.com/8994495/27648454-8871e78a-5c26-11e7-8be3-53f8be3cf348.png)

I'm able to replicate the stunted/shrunken down look by toggling Desktop mode and shrinking the browser window.

**Comment by yiskah** [comment]
It happens on both my work computer, which is 1388x something something, and my personal computer at home, which is 1920x1080 on firefox in windows 10

**Comment by marrus-sh** [comment]
This is fixed as of 595c6de32c052f2a5e21307a0e43a6bd5d4b5c88; the minimum size of the compose window has been increased to 300px, which is the same as upstream
