### ISSUE TITLE
Migrating from Mastodon to glitch-soc?

### ISSUE THREAD

**Issue by ProgVal** [glitch-soc/mastodon#500]
Hi,

Considering the project management issues of Mastodon, I am considering migrating [my instance](oc.todon.fr) to a community fork, and I have been pointed toward glitch-soc.

I have a few questions, I hope you don't mind them:

1. How does your project management work?
2. How risky is it to migrate from Mastodon 2.3.3 to glitch-soc?
3. How stable is glitch-soc, compared to a Mastodon release?
4. Are Mastodon's new features merged into glitch-soc? (I would assume yes given the "This branch is 1143 commits ahead, 2 commits behind tootsuite:master" on this repo's homepage, but I would like to make sure.)

Thank you!

**Comment by ThibG** [comment]
1. I… I actually don't know. I currently am the most active contributor on glitch-soc and haven't done anything related to managing the project yet.
2. There is no risk, but don't forget to run the migrations. I'm not sure how easy it would be to go back the other way if you changed your mind, though. You also need to know that the assets compilation step requires much more resources than vanilla Mastodon (mainly due to there being two front-ends).
3. It is less stable than Mastodon releases. Small breakages are somewhat frequent, and bigger issues (e.g., unusable WebUI in some configurations) do happen.
4. Back-end features are frequently merged into glitch-soc, but the “glitch” front-end has diverged, so it does not always get the new features as quickly. The “vanilla” front-end is still available and updated from upstream on a regular fashion.

**Comment by yipdw** [comment]
Some more info:

There isn't a formal management structure.  A lot of the discussion about it occurs here or on a Discord chat -- and I'm not really sure I can paste an invite link here, because I don't think we've ever hashed out whether the chat is public or private.

I think it is a good idea to go into glitch-soc with the expectation that the master branch is a place to play with Mastodon changes, and will likely stay that way.  This has led to some [useful features](https://glitch-soc.github.io/docs/) but comes at a cost to change control.  Some glitch-soc instances like [`dev.glitch.social`](https://dev.glitch.social/about/more) are set up with that expectation, but others are not.

There are plans for stable releases (see https://github.com/glitch-soc/mastodon/projects) but we haven't gotten too far on that.

**Comment by Tagadda** [comment]
Some more info again, about the migration process:

I recently migrated a Mastodon 2.3.3 instance from masto.host to glitch-soc hosted on my own server.

That was quite easy. I basically followed the [Migration Guide](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Migration-guide.md) and the [Production Guide](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md).
Just run a `RAILS_ENV=production bundle exec rails db:migrate` before you start the instance.

IIRC there's something about ruby version, like mastodon ruby v2.5.0 and glitch-soc ruby v2.5.1.
Anyway you'll have some errors, just read them and adapt your system o/

**Comment by ProgVal** [comment]
hmm. I use ruby 2.3 xD

**Comment by ThibG** [comment]
Closing as it is documented in https://glitch-soc.github.io/docs/#how-to-install-and-update-glitch-soc
