### ISSUE TITLE
CW textbox always open & bonus points for simple yes/no dialog optional

### ISSUE THREAD

**Issue by hoodieak** [glitch-soc/mastodon#634]
it's pretty simple/near the title!

essentially just a setting where the cw toggle dissappears and it remains always open as a textbox.

optional bonus points: textbox in dialog that can be chosen separately from CW always open, that pops up a 'are you sure you want to post without a content warning?', and following that, maybe even a textbox auto-selected to put the CW into a textbox in the dialog for style points

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by hoodieak** [comment]
see also: https://github.com/unascribed/sleeping.town/issues/43

una might beat us to it, and whoever does will be able to contribute and such over to here too !!

**Comment by JaredLethal** [comment]
i'm totally in for a default-opened CW textbox (like on pleroma even if it's called "subject" there) but i'm pretty sure a "are you sure" popup would be REALLY annoying REALLY fast. ;)

**Comment by ThibG** [comment]
I'm not completely sure I fully understand your requests, so let me reword them how I understand them:
1. Have a setting so that the CW field is always open (and the toggle hidden since it is useless)
2. Have an additional setting that asks for confirmation when publishing toots without a content warning.
3. As an improvement to the aforementioned dialog, have it contain an auto-focused input field to set the CW.

Is that what you are asking for? If so, I think 1. would be useful and easy to implement, I will do that when I'm finished with other stuff.

I'm afraid that 2 might get very annoying very fast, so I'm not too sure how useful that would be. But I may try implementing it, and it would be cool for you to somehow test it for real to see if that fits your usage (in which case I will consider adding it an option) or if it's just too annoying.

As for the third point, I would suggest not having an input in the dialog, but auto-focusing the CW field when the dialog is canceled.

**Comment by hoodieak** [comment]
ideally it would be an optional seperate toggle.

**Comment by hoodieak** [comment]
2/3 are both a separate feature entirely. option 1 is a toggle, and options 2/3 are a second toggle that can only be activated if toggle 1 is already set to be true
