### ISSUE TITLE
Add option to unfold all CWs but those matching specific keywords

### ISSUE THREAD

**Issue by ThibG** [glitch-soc/mastodon#678]
Add an (opt-in) option to unfold all CWs except those matching specific keywords (or regexps).

We could also use a whitelist-based approach but I'm not sure how to make that work.

Requests for this feature:
- https://plero.ma/notice/888107
- https://github.com/glitch-soc/mastodon/pull/664#issuecomment-415474130

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ThibG** [comment]
The thing is a blacklist model seems “easy” (hide if any substring/word of the CW matches any keyword/regexp) while a whitelist using the same behavior wouldn't work: unfolding if any substring matches the keyword is unsafe. And on the other hand, requiring the CW to exactly match the filter seems like it's not going to match a lot of CWs

**Comment by velartrill** [comment]
that's a really good point. ftr i think it's fairly safe to split tws on punctuation and test each string separately against the regex to make sure they all match, as long as the user is apprised of this behavior in advance. i've never seen anything but commas used to separate tws.

_but,_ that's nontrivial and it's a fairly complex behavior to expect users, especially non-technical ones, to understand. _especially_ since it's a behavior they'd be relying on to protect them from psychologically harmful material, meaning fuckups could be costly.

my instinct is, go with blacklisting by default and if some people _really_ want whitelist functionality, they can figure out a regex that'll do what they want at their own risk. but first i'd want to know if anyone could think of a solid enough use case for a whitelist feature that it's worth trying to find some way to develop the idea further.
