### ISSUE TITLE
Transform /me on name and write italic sentence

### ISSUE THREAD

**Issue by Dryusdan** [glitch-soc/mastodon#748]
I
I like a feature in irc, xmpp or matrix : /me
I'd like to know if that's possible to create /me command in Mastodon ?

Regard :)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ashkitten** [comment]
technically possible? sure. i'd encourage a more complete text styling implementation instead if you really want it, possibly with markdown syntax. my vote in any case is not to implement this in glitchsoc, since this software is oriented toward microblogging and not full length articles or whatever.

**Comment by ashkitten** [comment]
as i said before, this would be perfect for a personal fork but i don't think glitchsoc is the right place for it

**Comment by ThibG** [comment]
I don't really like “/me”, especially since I don't know exactly how we should render it, where it should be handled, etc.

As for Markdown, it's something I'm interested in, but it's pretty far down my priority list.

**Comment by Dryusdan** [comment]
> As for Markdown, it's something I'm interested in, but it's pretty far down my priority list. 

I understand, you make a very good and heavy job for mastodon :)
