### ISSUE TITLE
Don't go back to toot text when adding alt text to multiple pictures

### ISSUE THREAD

**Issue by sapphaos** [glitch-soc/mastodon#855]
This happens on both computer and mobile, with Firefox.

When adding multiple pictures and trying to add alt text to it, the behavior is really off putting. 
The first alt text gets added with expected behavior, but when you immediately click on the the second picture/zone for alt text it takes you back where your cursor was in the toot text. And it does that for every picture after the first one.

If you don't pay attention, you end up writing the alt text into the toot text, sometimes in the middle of a word if that's where your cursor was.

* * * *
(Hope you'll like the inspiring citation on my example pic)

![svid_20181215_092149](https://user-images.githubusercontent.com/26595575/50040922-89261680-004c-11e9-8aa1-128c56f1a702.gif)

**Comment by ThibG** [comment]
This happens because the logic for handling media file description changes is shared with that of submitting the toot in order to prevent submitting a toot mid-API request.
When a toot has been submitted or a media description changed, the compose textarea gets focused.
There are other issues with this logic: whenever a media description is being changed, the compose textarea is disabled, which is not necessary and can be confusing.
